name: Update Google Scholar Stats

on:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间 12:00 运行
  workflow_dispatch:       # 允许手动触发
  push:
    branches: [ main ]


jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run stats update script
      env:
        SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
      run: python update_stats.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        git diff --staged --quiet || git commit -m "Update scholar stats - $(date)"
        git push
